from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pn_settings(object):
    def setupUi(self, pn_settings_widget):
        pn_settings_widget.setObjectName("pn_settings_widget")
        pn_settings_widget.resize(504, 258)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(pn_settings_widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(pn_settings_widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.interception_list = QtWidgets.QListWidget(pn_settings_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.interception_list.sizePolicy().hasHeightForWidth())
        self.interception_list.setSizePolicy(sizePolicy)
        self.interception_list.setMaximumSize(QtCore.QSize(150, 16777215))
        self.interception_list.setObjectName("interception_list")
        self.verticalLayout.addWidget(self.interception_list)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_interception_btn = QtWidgets.QToolButton(pn_settings_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_interception_btn.sizePolicy().hasHeightForWidth())
        self.add_interception_btn.setSizePolicy(sizePolicy)
        self.add_interception_btn.setObjectName("add_interception")
        self.horizontalLayout.addWidget(self.add_interception_btn)
        self.remove_interception_btn = QtWidgets.QToolButton(pn_settings_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove_interception_btn.sizePolicy().hasHeightForWidth())
        self.remove_interception_btn.setSizePolicy(sizePolicy)
        self.remove_interception_btn.setObjectName("remove_interception")
        self.horizontalLayout.addWidget(self.remove_interception_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.settings_frame = QtWidgets.QFrame(pn_settings_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_frame.sizePolicy().hasHeightForWidth())
        self.settings_frame.setSizePolicy(sizePolicy)
        self.settings_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.settings_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.settings_frame.setObjectName("settings_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.settings_frame)
        self.verticalLayout_2.setContentsMargins(6, 0, 6, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.settings_label = QtWidgets.QLabel(self.settings_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_label.sizePolicy().hasHeightForWidth())
        self.settings_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.settings_label.setFont(font)
        self.settings_label.setObjectName("settings_label")
        self.verticalLayout_2.addWidget(self.settings_label)
        self.settings_box = QtWidgets.QGroupBox(self.settings_frame)
        self.settings_box.setObjectName("settings_box")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.settings_box)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.notify_opt = QtWidgets.QRadioButton(self.settings_box)
        self.notify_opt.setObjectName("notify_opt")
        self.verticalLayout_3.addWidget(self.notify_opt)
        self.time_limit_opt = QtWidgets.QRadioButton(self.settings_box)
        self.time_limit_opt.setObjectName("time_limit_opt")
        self.verticalLayout_3.addWidget(self.time_limit_opt)
        self.block_entirely_opt = QtWidgets.QRadioButton(self.settings_box)
        self.block_entirely_opt.setObjectName("block_entirely_opt")
        self.verticalLayout_3.addWidget(self.block_entirely_opt)
        self.motivate_opt = QtWidgets.QRadioButton(self.settings_box)
        self.motivate_opt.setObjectName("motivate_opt")
        self.notify_type_group = QtWidgets.QButtonGroup()
        self.notify_type_group.addButton(self.notify_opt)
        self.notify_type_group.addButton(self.time_limit_opt)
        self.notify_type_group.addButton(self.block_entirely_opt)
        self.notify_type_group.addButton(self.motivate_opt)
        self.verticalLayout_3.addWidget(self.motivate_opt)
        self.verticalLayout_2.addWidget(self.settings_box)
        self.interval_box = QtWidgets.QGroupBox(self.settings_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.interval_box.sizePolicy().hasHeightForWidth())
        self.interval_box.setSizePolicy(sizePolicy)
        self.interval_box.setObjectName("interval_box")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.interval_box)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.interval_number = QtWidgets.QSpinBox(self.interval_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.interval_number.sizePolicy().hasHeightForWidth())
        self.interval_number.setSizePolicy(sizePolicy)
        self.interval_number.setMaximum(1440)
        self.interval_number.setObjectName("interval_number")
        self.horizontalLayout_3.addWidget(self.interval_number)
        self.label_2 = QtWidgets.QLabel(self.interval_box)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.verticalLayout_2.addWidget(self.interval_box)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.apply_button = QtWidgets.QToolButton(self.settings_frame)
        self.apply_button.setObjectName("toolButton")
        self.horizontalLayout_4.addWidget(self.apply_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2.addWidget(self.settings_frame)

        self.retranslateUi(pn_settings_widget)
        QtCore.QMetaObject.connectSlotsByName(pn_settings_widget)

    def retranslateUi(self, pn_settings_widget):
        _translate = QtCore.QCoreApplication.translate
        pn_settings_widget.setWindowTitle(_translate("pn_settings_widget", "Procrastinot"))
        self.label.setText(_translate("pn_settings_widget", "Interception List"))
        __sortingEnabled = self.interception_list.isSortingEnabled()
        self.add_interception_btn.setText(_translate("pn_settings_widget", "ADD"))
        self.remove_interception_btn.setText(_translate("pn_settings_widget", "REMOVE"))
        self.settings_label.setText(_translate("pn_settings_widget", "Settings"))
        self.settings_box.setTitle(_translate("pn_settings_widget", "When I run a blacklisted program"))
        self.notify_opt.setText(_translate("pn_settings_widget", "Notify me before I run it to do something productive"))
        self.time_limit_opt.setText(_translate("pn_settings_widget", "Notify me before I run it to do something productive,\n"
"and also block me from running it for X amount of time"))
        self.block_entirely_opt.setText(_translate("pn_settings_widget", "Block the program from being ran entirely"))
        self.motivate_opt.setText(_translate("pn_settings_widget", "Force me to watch a motivational video before running it"))
        self.interval_box.setTitle(_translate("pn_settings_widget", "Notify me before opening a blacklisted program"))
        self.label_2.setText(_translate("pn_settings_widget", "minutes after not opening it beforehand"))
        self.apply_button.setText(_translate("pn_settings_widget", "   APPLY SETTINGS   "))

class Ui_halt(object):
    def setupUi(self, halt):
        halt.setObjectName("halt")
        halt.resize(335, 389)
        self.verticalLayout = QtWidgets.QVBoxLayout(halt)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(halt)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.title_label.setFont(font)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setWordWrap(True)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)
        self.summary_label = QtWidgets.QLabel(halt)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.summary_label.setFont(font)
        self.summary_label.setWordWrap(True)
        self.summary_label.setObjectName("summary_label")
        self.verticalLayout.addWidget(self.summary_label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.continue_button = QtWidgets.QPushButton(halt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.continue_button.sizePolicy().hasHeightForWidth())
        self.continue_button.setSizePolicy(sizePolicy)
        self.continue_button.setMinimumSize(QtCore.QSize(0, 50))
        self.continue_button.setObjectName("continue_button")
        self.verticalLayout.addWidget(self.continue_button)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.bullet_group = QtWidgets.QGroupBox(halt)
        self.bullet_group.setObjectName("bullet_group")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.bullet_group)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.bullet_1 = QtWidgets.QLabel(self.bullet_group)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bullet_1.setFont(font)
        self.bullet_1.setObjectName("bullet_1")
        self.verticalLayout_3.addWidget(self.bullet_1)
        self.bullet_2 = QtWidgets.QLabel(self.bullet_group)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bullet_2.setFont(font)
        self.bullet_2.setObjectName("bullet_2")
        self.verticalLayout_3.addWidget(self.bullet_2)
        self.bullet_3 = QtWidgets.QLabel(self.bullet_group)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bullet_3.setFont(font)
        self.bullet_3.setObjectName("bullet_3")
        self.verticalLayout_3.addWidget(self.bullet_3)
        self.bullet_4 = QtWidgets.QLabel(self.bullet_group)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bullet_4.setFont(font)
        self.bullet_4.setObjectName("bullet_4")
        self.verticalLayout_3.addWidget(self.bullet_4)
        self.bullet_5 = QtWidgets.QLabel(self.bullet_group)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bullet_5.setFont(font)
        self.bullet_5.setObjectName("bullet_5")
        self.verticalLayout_3.addWidget(self.bullet_5)
        self.verticalLayout.addWidget(self.bullet_group)

        self.retranslateUi(halt)
        QtCore.QMetaObject.connectSlotsByName(halt)

    def retranslateUi(self, halt):
        _translate = QtCore.QCoreApplication.translate
        halt.setWindowTitle(_translate("halt", "Don\'t Procrastinate!"))
        self.title_label.setText(_translate("halt", "Don\'t Procrastinate!"))
        self.continue_button.setText(_translate("halt", "Continue"))
        self.bullet_group.setTitle(_translate("halt", "Here are a few ideas of what you can do instead"))
        self.bullet_1.setText(_translate("halt", "- Finish any assignments / homework you may have"))
        self.bullet_2.setText(_translate("halt", "- Learn a new skill"))
        self.bullet_3.setText(_translate("halt", "- Learn to code"))
        self.bullet_4.setText(_translate("halt", "- Go to the gym"))
        self.bullet_5.setText(_translate("halt", "- Go outside!"))